name: Expo Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        username: [EXPO_CLI_USERNAME, EXPO_CLI_USERNAME_ALIAS]
        password: [EXPO_CLI_PASSWORD, EXPO_CLI_PASSWORD_ALIAS]
        exclude:
          - username: EXPO_CLI_USERNAME
            password: EXPO_CLI_PASSWORD_ALIAS
          - username: EXPO_CLI_USERNAME_ALIAS
            password: EXPO_CLI_PASSWORD
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets[matrix.username] }}
          expo-password: ${{ secrets[matrix.password] }}
          expo-cache: true
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Publish to Expo
        run: expo publish
